import { 
    Utensils, Zap, Cake, Soup, Coffee, XCircle, 
    TrendingUp, TrendingDown, Clock, Lightbulb, ChefHat, Star, Timer
} from 'lucide-react'

// ====================================================================
// --- 1. Utility Icons Map ---
// ====================================================================
export const ICON_MAP = {
    Search: Zap, 
    Utensils,
    Cake,
    Soup,
    Coffee,
    XCircle,
    TrendingUp,
    TrendingDown,
    Clock,
    Lightbulb,
    ChefHat,
    Star,
    Timer,
}

// ====================================================================
// --- 2. Filter Data Definitions ---
// ====================================================================
export const categories = [
    { name: "All Recipes", filter: null, icon: Utensils },
    { name: "Main Dishes", filter: "Main Dish", icon: ChefHat },
    { name: "Bakes & Pastries", filter: "Baking", icon: Cake },
    { name: "Snacks & Appetizers", filter: "Snacks", icon: Coffee },
    { name: "Sides & Staples", filter: "Side Dish", icon: Zap },
]

export const difficulties = [
    { name: "All Levels", filter: null, icon: Clock },
    { name: "Easy", filter: "Easy", icon: TrendingDown },
    { name: "Medium", filter: "Medium", icon: TrendingUp },
    { name: "Advanced", filter: "Hard", icon: Lightbulb },
]

// ====================================================================
// --- 3. Mock Recipe Data (Full Details for Slug Pages) ---
// ====================================================================
export const allRecipes = [
    // Bakes & Pastries (Total: 8)
    { 
        id: 1, 
        title: "Classic Meat Pie", 
        category: "Baking", 
        prepTime: "30 min", 
        cookTime: "1 hr", 
        tags: ["Savoury", "Snack", "Beef"], 
        image: "meatpie.jpg", 
        slug: "classic-meat-pie", 
        excerpt: "Flaky crust enclosing perfectly seasoned savory beef filling. A comforting classic.", 
        rating: 4.8, 
        difficulty: "Medium",
        ingredients: [
            { item: "All-Purpose Flour", qty: "300", unit: "g" },
            { item: "Cold Butter (diced)", qty: "150", unit: "g" },
            { item: "Ground Beef", qty: "500", unit: "g" },
            { item: "Chopped Onion", qty: "1", unit: "medium" },
            { item: "Beef Broth", qty: "250", unit: "ml" },
            { item: "Worcestershire Sauce", qty: "1", unit: "tbsp" },
            { item: "Egg Yolk", qty: "1", unit: "" },
            { item: "Salt & Pepper", qty: "To", unit: "taste" },
        ],
        instructions: [
            "Prepare the Pastry: Combine flour and cold butter until it resembles coarse crumbs. Add iced water gradually to form a dough. Chill for 30 minutes.",
            "Make the Filling: Brown the ground beef and drain excess fat. Add onions, salt, pepper, and cook until tender. Stir in the broth and Worcestershire sauce. Reduce heat and simmer for 10 minutes to thicken.",
            "Assemble the Pie: Roll out half the pastry and line a 9-inch pie dish. Scoop in the cooled filling. Top with the remaining pastry, crimp the edges, and cut vents.",
            "Bake: Brush with egg yolk wash. Bake at 190°C (375°F) for 50-60 minutes or until golden brown. Let cool slightly before serving.",
        ]
    },
    { 
        id: 2, 
        title: "Creamy Chicken Pie", 
        category: "Baking", 
        prepTime: "35 min", 
        cookTime: "1 hr 15 min", 
        tags: ["Savoury", "Dinner", "Chicken"], 
        image: "piee.jpg", 
        slug: "creamy-chicken-pie", 
        excerpt: "Tender chicken in a rich, velvety cream sauce, baked under a golden puff pastry.", 
        rating: 4.5, 
        difficulty: "Medium",
        ingredients: [
            { item: "Cooked Chicken Breast (diced)", qty: "400", unit: "g" },
            { item: "Puff Pastry Sheets", qty: "2", unit: "" },
            { item: "Heavy Cream", qty: "200", unit: "ml" },
            { item: "Chopped Mushrooms", qty: "1", unit: "cup" },
            { item: "Thyme", qty: "1/2", unit: "tsp" },
            { item: "Flour (for roux)", qty: "2", unit: "tbsp" },
            { item: "Chicken Stock", qty: "200", unit: "ml" },
            { item: "Salt, Pepper, Egg Wash", qty: "To", unit: "taste" },
        ],
        instructions: [
            "Start the Roux: Melt butter, whisk in flour, and cook for 1 minute. Gradually whisk in chicken stock until smooth, then add heavy cream and simmer until thickened.",
            "Assemble Filling: Stir in diced chicken, mushrooms, and thyme. Season with salt and pepper. Allow the filling to cool slightly.",
            "Pie Assembly: Line a pie dish with one sheet of pastry. Pour in the filling. Cover with the second sheet, seal the edges, and cut vents.",
            "Bake: Brush with egg wash. Bake at 200°C (400°F) for 35-40 minutes or until the pastry is golden and puffed.",
        ]
    },
    { 
        id: 3, 
        title: "Artisan Sourdough Bread", 
        category: "Baking", 
        prepTime: "20 min", 
        cookTime: "4 hr", 
        tags: ["Bread", "Vegan", "Fermented"], 
        image: "sour.jpg", 
        slug: "sourdough-bread", 
        excerpt: "Achieve the perfect open crumb and signature tangy flavor with this method.", 
        rating: 4.9, 
        difficulty: "Hard",
        ingredients: [
            { item: "Active Sourdough Starter", qty: "100", unit: "g" },
            { item: "Bread Flour", qty: "400", unit: "g" },
            { item: "Whole Wheat Flour", qty: "100", unit: "g" },
            { item: "Lukewarm Water", qty: "350", unit: "ml" },
            { item: "Fine Sea Salt", qty: "10", unit: "g" },
        ],
        instructions: [
            "The Autolyse: Mix the flours and water until just combined. Let rest for 30 minutes to hydrate the flour.",
            "Mix and Bulk Ferment: Incorporate the starter and salt. Mix thoroughly. Perform 4 sets of stretch and folds over the first 2 hours of bulk fermentation.",
            "Shape and Cold Proof: Shape the dough gently into a tight ball (boule) and place it seam-side up in a floured banneton basket. Refrigerate overnight (12-18 hours).",
            "Bake: Preheat a Dutch oven to 260°C (500°F). Score the dough, place it in the Dutch oven, and bake covered for 20 minutes, then uncovered for 25-30 minutes until deep golden brown.",
        ]
    },
    { 
        id: 4, 
        title: "Moist Banana Bread", 
        category: "Baking", 
        prepTime: "15 min", 
        cookTime: "50 min", 
        tags: ["Bread", "Sweet", "Quick"], 
        image: "moist.jpg", 
        slug: "banana-bread", 
        excerpt: "Simple, moist, and spiced. The best way to use up those ripe bananas!", 
        rating: 4.7, 
        difficulty: "Easy",
        ingredients: [
            { item: "Ripe Bananas (mashed)", qty: "3", unit: "medium" },
            { item: "All-Purpose Flour", qty: "1.5", unit: "cups" },
            { item: "Granulated Sugar", qty: "3/4", unit: "cup" },
            { item: "Unsalted Butter (melted)", qty: "1/2", unit: "cup" },
            { item: "Large Egg", qty: "1", unit: "" },
            { item: "Baking Soda", qty: "1", unit: "tsp" },
            { item: "Vanilla Extract", qty: "1", unit: "tsp" },
            { item: "Cinnamon", qty: "1/2", unit: "tsp" },
            { item: "Salt", qty: "1/4", unit: "tsp" },
        ],
        instructions: [
            "Preheat & Prep: Preheat oven to 175°C (350°F). Grease and flour a 9x5 inch loaf pan.",
            "Wet Ingredients: In a large bowl, whisk together the melted butter, mashed bananas, egg, and vanilla until just combined.",
            "Dry Ingredients: In a separate bowl, mix flour, sugar, baking soda, cinnamon, and salt.",
            "Combine: Gently fold the dry ingredients into the wet ingredients until just combined. Do not overmix! A few lumps are okay.",
            "Bake: Pour batter into the prepared loaf pan. Bake for 50-60 minutes. A toothpick inserted into the center should come out clean. Cool for 10 minutes before slicing.",
        ]
    },
    { 
        id: 5, 
        title: "Vanilla Cupcakes", 
        category: "Baking", 
        prepTime: "20 min", 
        cookTime: "25 min", 
        tags: ["Sweet", "Dessert", "Party"], 
        image: "cup.jpg", 
        slug: "vanilla-cupcakes", 
        excerpt: "Light, airy vanilla sponge topped with fluffy buttercream. A foolproof basic.", 
        rating: 4.4, 
        difficulty: "Easy",
        ingredients: [
            { item: "All-Purpose Flour", qty: "1.5", unit: "cups" },
            { item: "Granulated Sugar", qty: "1", unit: "cup" },
            { item: "Baking Powder", qty: "1.5", unit: "tsp" },
            { item: "Salt", qty: "1/4", unit: "tsp" },
            { item: "Milk", qty: "1/2", unit: "cup" },
            { item: "Unsalted Butter (softened)", qty: "1/2", unit: "cup" },
            { item: "Large Eggs", qty: "2", unit: "" },
            { item: "Vanilla Extract", qty: "2", unit: "tsp" },
        ],
        instructions: [
            "Mix Dry: Whisk together flour, sugar, baking powder, and salt in a large bowl.",
            "Add Wet: Add softened butter, milk, eggs, and vanilla. Beat on low speed until combined, then increase to medium and beat for 2 minutes until batter is light and fluffy.",
            "Portion: Fill cupcake liners 2/3 full.",
            "Bake: Bake at 175°C (350°F) for 20-25 minutes. Cool completely on a wire rack before frosting.",
        ]
    },
    { 
        id: 6, 
        title: "Rich Chocolate Cake", 
        category: "Baking", 
        prepTime: "40 min", 
        cookTime: "1 hr 10 min", 
        tags: ["Sweet", "Celebration", "Decadent"], 
        image: "cake.jpg", 
        slug: "chocolate-cake", 
        excerpt: "Intensely dark and fudgy cake with a rich ganache. Perfect for special occasions.", 
        rating: 4.9, 
        difficulty: "Medium",
        ingredients: [
            { item: "All-Purpose Flour", qty: "2", unit: "cups" },
            { item: "Cocoa Powder (unsweetened)", qty: "3/4", unit: "cup" },
            { item: "Baking Soda", qty: "2", unit: "tsp" },
            { item: "Sugar", qty: "2", unit: "cups" },
            { item: "Buttermilk", qty: "1", unit: "cup" },
            { item: "Vegetable Oil", qty: "1/2", unit: "cup" },
            { item: "Large Eggs", qty: "2", unit: "" },
            { item: "Hot Coffee", qty: "1", unit: "cup" },
        ],
        instructions: [
            "Mix Dry: Sift and whisk flour, cocoa, baking soda, and sugar in a large bowl.",
            "Wet Ingredients: Add buttermilk, oil, and eggs to the dry mix. Beat on medium speed for 2 minutes.",
            "Final Batter: Carefully stir in the hot coffee (or water). The batter will be thin.",
            "Bake: Pour into two 9-inch round pans. Bake at 180°C (350°F) for 30-35 minutes. Cool completely before assembling and frosting with a rich ganache.",
        ]
    },
    { 
        id: 7, 
        title: "Fluffy Donuts", 
        category: "Baking", 
        prepTime: "45 min", 
        cookTime: "30 min", 
        tags: ["Sweet", "Snack", "Fried"], 
        image: "donut.jpg", 
        slug: "fluffy-donuts", 
        excerpt: "Yeast-risen dough, fried to a perfect golden brown, ready for glazing or dusting.", 
        rating: 4.3, 
        difficulty: "Medium",
        ingredients: [
            { item: "All-Purpose Flour", qty: "3.5", unit: "cups" },
            { item: "Active Dry Yeast", qty: "2.25", unit: "tsp" },
            { item: "Warm Milk", qty: "1", unit: "cup" },
            { item: "Granulated Sugar", qty: "1/4", unit: "cup" },
            { item: "Large Egg", qty: "1", unit: "" },
            { item: "Butter (softened)", qty: "4", unit: "tbsp" },
            { item: "Vegetable Oil", qty: "As needed", unit: "for frying" },
        ],
        instructions: [
            "Activate Yeast: Mix yeast and sugar in warm milk; let stand 5 minutes until foamy.",
            "Mix Dough: Combine flour and salt. Add the yeast mixture, egg, and butter. Knead until a smooth dough forms (about 5-7 minutes).",
            "Proofing: Place in an oiled bowl, cover, and let rise for 1-1.5 hours until doubled.",
            "Cut and Fry: Roll dough to 1/2-inch thickness. Cut with a donut cutter. Let rest 15 minutes. Fry in 175°C (350°F) oil, 1-2 minutes per side until golden. Drain and glaze.",
        ]
    },
    { 
        id: 8, 
        title: "Savory Sausage Rolls", 
        category: "Baking", 
        prepTime: "20 min", 
        cookTime: "40 min", 
        tags: ["Savoury", "Snack", "Pork"], 
        image: "rolls.jpg", 
        slug: "sausage-rolls", 
        excerpt: "Juicy, spiced sausage meat wrapped in golden puff pastry. Excellent appetizer.", 
        rating: 4.6, 
        difficulty: "Easy",
        ingredients: [
            { item: "Puff Pastry Sheets", qty: "2", unit: "" },
            { item: "Pork Sausage Meat (uncased)", qty: "500", unit: "g" },
            { item: "Finely Diced Onion", qty: "1/2", unit: "cup" },
            { item: "Breadcrumbs", qty: "1/4", unit: "cup" },
            { item: "Egg (for binding)", qty: "1", unit: "" },
            { item: "Fennel Seeds (optional)", qty: "1/2", unit: "tsp" },
            { item: "Egg (for wash)", qty: "1", unit: "" },
        ],
        instructions: [
            "Prepare Filling: In a bowl, mix sausage meat, diced onion, breadcrumbs, the binding egg, fennel seeds, salt, and pepper until well combined.",
            "Assemble: Cut each pastry sheet in half lengthwise. Form the meat mixture into long, thin logs and place them down the center of each pastry strip.",
            "Roll and Cut: Brush one edge of the pastry with egg wash, fold the pastry over the meat log, and press the edges to seal. Cut into 2-inch rolls.",
            "Bake: Brush the top of the rolls with egg wash. Bake at 200°C (400°F) for 25-30 minutes until the pastry is golden and the meat is cooked through.",
        ]
    },
    
    // Snacks & Finger Foods (Total: 3)
    { 
        id: 9, 
        title: "Yogurt Parfait", 
        category: "Snacks", 
        prepTime: "10 min", 
        cookTime: "0 min", 
        tags: ["Healthy", "Breakfast", "No-Cook"], 
        image: "parf.jpg", 
        slug: "yogurt-parfait", 
        excerpt: "Layers of Greek yogurt, berries, and crunchy granola. Quick and nutritious.", 
        rating: 4.2, 
        difficulty: "Easy",
        ingredients: [
            { item: "Greek Yogurt (plain)", qty: "1", unit: "cup" },
            { item: "Mixed Berries (fresh or frozen)", qty: "1/2", unit: "cup" },
            { item: "Granola (high-fiber)", qty: "1/4", unit: "cup" },
            { item: "Honey or Maple Syrup", qty: "1", unit: "tbsp" },
        ],
        instructions: [
            "Base Layer: Spoon 1/4 cup of yogurt into the bottom of a glass or jar.",
            "Fruit Layer: Top the yogurt with a layer of berries and a drizzle of honey.",
            "Crunch Layer: Sprinkle 1/3 of the granola over the fruit.",
            "Repeat: Add another layer of yogurt, then the remaining fruit and granola. Serve immediately or chill for up to 4 hours.",
        ]
    },
    { 
        id: 10, 
        title: "Crispy Egg Rolls", 
        category: "Snacks", 
        prepTime: "40 min", 
        cookTime: "20 min", 
        tags: ["Appetizer", "Fried", "Vegetable"], 
        image: "egg.jpg", 
        slug: "crispy-egg-rolls", 
        excerpt: "Classic Asian appetizer with a perfect crunch and savory filling.", 
        rating: 4.5, 
        difficulty: "Medium",
        ingredients: [
            { item: "Egg Roll Wrappers", qty: "12", unit: "" },
            { item: "Shredded Cabbage", qty: "2", unit: "cups" },
            { item: "Shredded Carrots", qty: "1", unit: "cup" },
            { item: "Ground Pork or Beef (optional)", qty: "200", unit: "g" },
            { item: "Soy Sauce", qty: "1", unit: "tbsp" },
            { item: "Ginger (minced)", qty: "1", unit: "tsp" },
            { item: "Sesame Oil", qty: "1", unit: "tsp" },
            { item: "Vegetable Oil", qty: "For deep frying", unit: "" },
        ],
        instructions: [
            "Prepare Filling: Sauté pork (if using) until cooked. Add cabbage, carrots, soy sauce, ginger, and sesame oil. Cook until vegetables are tender-crisp. Cool completely.",
            "Assemble: Place a wrapper on a flat surface. Spoon 2 tbsp of filling onto the lower third. Fold the bottom corner over the filling, fold in the sides, and roll tightly.",
            "Seal: Use water on the final corner to seal the roll tightly.",
            "Fry: Fry in 180°C (350°F) oil for 3-4 minutes, turning frequently, until golden brown and crispy. Drain on paper towels and serve with sweet chili sauce.",
        ]
    },
    { 
        id: 11, 
        title: "Spicy Puff Puff", 
        category: "Snacks", 
        prepTime: "1 hr", 
        cookTime: "25 min", 
        tags: ["Fried", "Dessert", "West African"], 
        image: "puff.jpg", 
        slug: "spicy-puff-puff", 
        excerpt: "Soft, spongy, yeast-risen dough balls, lightly spiced and fried. A favorite street snack.", 
        rating: 4.1, 
        difficulty: "Medium",
        ingredients: [
            { item: "All-Purpose Flour", qty: "3", unit: "cups" },
            { item: "Active Dry Yeast", qty: "2", unit: "tsp" },
            { item: "Sugar", qty: "1/2", unit: "cup" },
            { item: "Nutmeg", qty: "1/2", unit: "tsp" },
            { item: "Warm Water", qty: "1.5", unit: "cups" },
            { item: "Salt", qty: "1/2", unit: "tsp" },
            { item: "Chili Powder (optional)", qty: "1/4", unit: "tsp" },
            { item: "Vegetable Oil", qty: "For deep frying", unit: "" },
        ],
        instructions: [
            "Activate Yeast: Mix yeast and 1 tbsp sugar in warm water. Let rest 10 minutes.",
            "Make Batter: In a large bowl, combine flour, remaining sugar, salt, nutmeg, and chili powder. Pour in the yeast mixture and stir until a smooth, thick batter forms.",
            "Proofing: Cover the bowl and let it rise in a warm place for 45 minutes to 1 hour, or until doubled and bubbly.",
            "Fry: Scoop the batter using a small scoop or your hand (traditional method) into 180°C (350°F) oil. Fry until golden brown, about 3 minutes, flipping constantly. Drain and serve warm.",
        ]
    },
    
    // Main Dishes & Sides (Total: 14)
    { 
        id: 12, 
        title: "Steamed Moi Moi", 
        category: "Main Dish", 
        prepTime: "30 min", 
        cookTime: "1 hr", 
        tags: ["Traditional", "Healthy", "Vegan Option"], 
        image: "moimoi.jpg", 
        slug: "moi-moi", 
        excerpt: "Nutritious pudding made from steamed ground beans, often paired with Jollof or rice.", 
        rating: 4.7, 
        difficulty: "Hard",
        ingredients: [
            { item: "Brown/Black-Eyed Beans (peeled)", qty: "2", unit: "cups" },
            { item: "Red Bell Pepper", qty: "1", unit: "large" },
            { item: "Scotch Bonnet Pepper", qty: "1-2", unit: "" },
            { item: "Onion", qty: "1", unit: "medium" },
            { item: "Palm Oil or Vegetable Oil", qty: "1/4", unit: "cup" },
            { item: "Fish/Chicken Stock", qty: "1/4", unit: "cup" },
            { item: "Seasoning Cubes", qty: "3", unit: "" },
            { item: "Boiled Eggs/Mackerel (fillers)", qty: "Optional", unit: "" },
        ],
        instructions: [
            "Blend Base: Blend the peeled beans with bell pepper, scotch bonnet, and onion, adding water sparingly until a smooth, thick batter is formed.",
            "Mix: Pour the batter into a large bowl. Whisk in oil, stock, seasoning cubes, and salt. Mix thoroughly to incorporate air, which aids fluffiness.",
            "Portion: Pour the batter into aluminum containers, plastic bowls, or wrapped banana leaves. Add fillers (eggs, fish) to each portion.",
            "Steam: Arrange the containers in a steamer pot. Steam for 45-60 minutes, checking with a toothpick until it comes out clean.",
        ]
    },
    { 
        id: 13, 
        title: "Party Jollof Rice", 
        category: "Main Dish", 
        prepTime: "45 min", 
        cookTime: "1 hr 15 min", 
        tags: ["Rice", "Traditional", "Celebration"], 
        image: "jollof.jpg", 
        slug: "party-jollof-rice", 
        excerpt: "The iconic smoky, spiced tomato-based rice. Master the perfect party recipe.", 
        rating: 5.0, 
        difficulty: "Medium",
        ingredients: [
            { item: "Long Grain Rice (parboiled)", qty: "4", unit: "cups" },
            { item: "Red Bell Peppers", qty: "6", unit: "large" },
            { item: "Plum Tomatoes", qty: "3", unit: "medium" },
            { item: "Scotch Bonnet Peppers", qty: "2-4", unit: "" },
            { item: "Tomato Paste", qty: "1/2", unit: "cup" },
            { item: "Chopped Onions", qty: "2", unit: "large" },
            { item: "Vegetable Oil", qty: "1/2", unit: "cup" },
            { item: "Chicken/Beef Stock", qty: "4", unit: "cups" },
            { item: "Bay Leaves", qty: "3", unit: "" },
            { item: "Curry Powder & Thyme", qty: "1", unit: "tsp each" },
        ],
        instructions: [
            "Prepare Pepper Mix: Blend the red bell peppers, plum tomatoes, and scotch bonnet until smooth. Fry the tomato paste in hot oil for 5 minutes.",
            "Make the Sauce Base: Pour the pepper blend into the fried paste and boil until the water evaporates and the sauce reduces significantly (about 20-30 min).",
            "Infuse Flavor: In a separate pot, heat oil, sauté onions, add the reduced sauce, stock, bay leaves, curry, and thyme. Season heavily with salt and bouillon cubes. Bring to a boil.",
            "Add Rice: Stir in the parboiled rice, mix well with the sauce, cover the pot tightly with foil/lid to trap steam, and reduce the heat to low.",
            "Achieve Smokiness: Allow the rice to cook on low heat for 30-45 minutes without opening the lid. The rice at the bottom will burn slightly, creating the signature 'smoky' party flavor.",
        ]
    },
    {
        id: 14,
        title: "Asun Jollof Fusion",
        category: "Main Dish",
        prepTime: "1 hr",
        cookTime: "1 hr 30 min",
        tags: ["Spicy", "Fusion", "Goat Meat"],
        image: "asun.jpg",
        slug: "asun-jollof",
        excerpt: "Jollof rice combined with spicy, grilled goat meat (Asun). Bold and complex flavors.",
        rating: 4.8,
        difficulty: "Hard",
        ingredients: [
            { item: "Long Grain Rice (parboiled)", qty: "4", unit: "cups" },
            { item: "Red Bell Peppers", qty: "6", unit: "large" },
            { item: "Plum Tomatoes", qty: "3", unit: "medium" },
            { item: "Scotch Bonnet Peppers", qty: "2-4", unit: "" },
            { item: "Tomato Paste", qty: "1/2", unit: "cup" },
            { item: "Chopped Onions", qty: "2", unit: "large" },
            { item: "Vegetable Oil", qty: "1/2", unit: "cup" },
            { item: "Chicken/Beef Stock", qty: "4", unit: "cups" },
            { item: "Bay Leaves", qty: "3", unit: "" },
            { item: "Curry Powder & Thyme", qty: "1", unit: "tsp each" },
            { item: "Goat Meat (cubed)", qty: "1", unit: "kg" },
            { item: "Habanero Peppers (extra for spice)", qty: "3", unit: "" },
            { item: "Bell Peppers (diced for garnish)", qty: "1/2", unit: "cup" },
            { item: "Ginger and Garlic Paste", qty: "1", unit: "tbsp" },
        ],
        instructions: [
            "Prep Asun: Boil goat meat with ginger/garlic paste and seasonings until tender. Drain and grill or oven-roast until slightly charred.",
            "Spice Sauce: Mix the charred goat meat with a separate, very spicy pepper mix (habanero, onion, oil).",
            "Cook Jollof: Follow steps 1-4 of the Party Jollof recipe (ID 13).",
            "Fusion: Once the Jollof rice is cooked, fold in the spicy Asun meat mixture and diced fresh bell peppers. Serve immediately, as the combination of textures is key.",
        ]
    },
    { 
        id: 15, 
        title: "Beans and Ripe Plantain", 
        category: "Main Dish", 
        prepTime: "10 min", 
        cookTime: "45 min", 
        tags: ["Traditional", "Vegan", "Comfort"], 
        image: "beans.jpg", 
        slug: "beans-plantain", 
        excerpt: "Hearty beans and sweet fried plantain (Dodo) cooked in a rich, palm oil sauce.", 
        rating: 4.3, 
        difficulty: "Easy",
        ingredients: [
            { item: "Black-Eyed Beans", qty: "2", unit: "cups" },
            { item: "Ripe Plantains", qty: "2", unit: "" },
            { item: "Palm Oil (or Vegetable Oil)", qty: "1/2", unit: "cup" },
            { item: "Tatashe/Bell Pepper (blended)", qty: "2", unit: "" },
            { item: "Onions (chopped)", qty: "1", unit: "medium" },
            { item: "Smoked Fish/Prawns (optional)", qty: "1/2", unit: "cup" },
            { item: "Salt and Seasoning Cubes", qty: "To", unit: "taste" },
        ],
        instructions: [
            "Boil Beans: Boil the beans until very soft, changing the water once halfway through. Drain excess water.",
            "Fry Sauce Base: Heat palm oil (or vegetable oil). Sauté chopped onions until translucent. Add blended pepper mix and cook for 10 minutes.",
            "Combine: Add the boiled beans to the sauce. Stir in seasoning cubes and salt. Add smoked fish/prawns if desired. Allow to simmer for 10-15 minutes until sauce thickens.",
            "Prepare Plantain (Dodo): Peel and slice plantain diagonally. Fry in a separate pan until golden brown. Serve the beans hot with the fried plantain on the side.",
        ]
    },
    { 
        id: 16, 
        title: "Spicy Gizzdodo", 
        category: "Side Dish", 
        prepTime: "20 min", 
        cookTime: "30 min", 
        tags: ["Spicy", "Appetizer", "Chicken Gizzard"], 
        image: "gizz.jpg", 
        slug: "gizzdodo", 
        excerpt: "A fantastic mix of fried gizzard and sweet plantain pieces tossed in pepper sauce.", 
        rating: 4.6, 
        difficulty: "Medium",
        ingredients: [
            { item: "Chicken Gizzards", qty: "500", unit: "g" },
            { item: "Ripe Plantains (cubed)", qty: "2", unit: "medium" },
            { item: "Red Bell Peppers", qty: "2", unit: "" },
            { item: "Scotch Bonnet Peppers", qty: "2", unit: "" },
            { item: "Onion (chopped)", qty: "1", unit: "medium" },
            { item: "Curry Powder & Thyme", qty: "To", unit: "taste" },
            { item: "Vegetable Oil", qty: "For frying", unit: "" },
        ],
        instructions: [
            "Prep Gizzard: Boil gizzards with curry, thyme, salt, and seasoning until tender. Drain and fry the gizzards until slightly crispy. Dice the fried gizzards.",
            "Fry Plantain: Fry the cubed plantain (Dodo) in oil until golden brown. Set aside.",
            "Make Sauce: Blend bell peppers and scotch bonnets. Sauté chopped onions, add the pepper blend, and cook until the oil floats to the top (about 10 minutes).",
            "Combine: Fold the diced fried gizzard and the fried plantain into the pepper sauce. Stir well to coat. Serve warm as an appetizer or side.",
        ]
    },
    { 
        id: 17, 
        title: "Classic Tomato Stew", 
        category: "Side Dish", 
        prepTime: "20 min", 
        cookTime: "1 hr", 
        tags: ["Sauce", "Staple", "Freezable"], 
        image: "toma.jpg", 
        slug: "tomato-stew", 
        excerpt: "The foundational Nigerian stew. Versatile and essential for pairing with staples.", 
        rating: 4.7, 
        difficulty: "Easy",
        ingredients: [
            { item: "Tomato Puree/Blended Fresh Tomatoes", qty: "500", unit: "g" },
            { item: "Red Bell Peppers (blended)", qty: "4", unit: "large" },
            { item: "Onions (chopped)", qty: "2", unit: "large" },
            { item: "Vegetable Oil", qty: "1", unit: "cup" },
            { item: "Garlic and Ginger (minced)", qty: "1", unit: "tbsp" },
            { item: "Meat or Fish Stock", qty: "1/2", unit: "cup" },
            { item: "Thyme and Curry Powder", qty: "1", unit: "tsp each" },
        ],
        instructions: [
            "Boil/Fry Base: Boil the blended tomato/pepper mix until water is completely evaporated. Alternatively, fry the base mix until the color darkens and the oil is absorbed.",
            "Sauté Aromatics: Heat oil, sauté half the chopped onions until golden. Add garlic and ginger.",
            "Add Tomato Base: Add the boiled/fried tomato base to the sautéed aromatics. Fry (or 'bleach') this mixture for 20-30 minutes, stirring constantly until the stew is no longer sour.",
            "Simmer: Add the stock, remaining onions, thyme, curry, salt, and seasoning cubes. Simmer for 15 minutes. Add cooked meat/fish and simmer for another 10 minutes. Serve with rice or yams.",
        ]
    },
    { 
        id: 18, 
        title: "Simple White Rice", 
        category: "Side Dish", 
        prepTime: "5 min", 
        cookTime: "25 min", 
        tags: ["Staple", "Quick", "Basic"], 
        image: "rice.jpg", 
        slug: "white-rice", 
        excerpt: "Tips and tricks for perfectly fluffy, non-sticky white rice every time.", 
        rating: 4.1, 
        difficulty: "Easy",
        ingredients: [
            { item: "White Rice (long grain)", qty: "2", unit: "cups" },
            { item: "Water", qty: "3.5", unit: "cups" },
            { item: "Salt", qty: "1", unit: "tsp" },
            { item: "Butter (optional)", qty: "1", unit: "tbsp" },
        ],
        instructions: [
            "Rinse: Rinse the rice thoroughly under cold water until the water runs clear. This removes excess starch.",
            "Boil: Combine rice, water, and salt in a pot. Bring to a rolling boil over high heat.",
            "Simmer: Reduce heat to the lowest setting immediately, cover tightly, and simmer for exactly 15 minutes. Do not lift the lid.",
            "Rest: Remove from heat (keep lid on) and let the rice rest for 10 minutes. Fluff with a fork before serving.",
        ]
    },
    { 
        id: 19, 
        title: "Perfect Fried Rice", 
        category: "Main Dish", 
        prepTime: "30 min", 
        cookTime: "40 min", 
        tags: ["Rice", "Quick", "Vegetarian"], 
        image: "fried.jpg", 
        slug: "fried-rice", 
        excerpt: "An easy, flavorful dish with mixed vegetables, protein, and a touch of soy sauce.", 
        rating: 4.5, 
        difficulty: "Medium",
        ingredients: [
            { item: "Day-Old Cooked White Rice", qty: "4", unit: "cups" },
            { item: "Mixed Vegetables (peas, carrots, corn)", qty: "2", unit: "cups" },
            { item: "Diced Chicken/Shrimp", qty: "200", unit: "g" },
            { item: "Soy Sauce (light)", qty: "3", unit: "tbsp" },
            { item: "Sesame Oil", qty: "1", unit: "tsp" },
            { item: "Eggs (scrambled)", qty: "2", unit: "" },
            { item: "Chopped Spring Onions", qty: "1/4", unit: "cup" },
        ],
        instructions: [
            "Prep: Ensure rice is cold and day-old; this prevents stickiness. Scramble eggs and set aside.",
            "Sauté: Heat oil in a wok or large pan. Sauté chicken/shrimp until cooked. Add mixed vegetables and cook for 3 minutes until tender-crisp.",
            "Fry Rice: Add the cold rice to the wok. Break up any clumps and stir-fry over high heat for 3-5 minutes. The high heat is key.",
            "Season and Finish: Push the rice to one side. Add soy sauce and sesame oil. Stir to combine. Fold in the scrambled eggs and spring onions. Serve immediately.",
        ]
    },
    { 
        id: 20, 
        title: "Egusi Soup", 
        category: "Main Dish", 
        prepTime: "40 min", 
        cookTime: "1 hr 20 min", 
        tags: ["Soup", "Traditional", "Heavy"], 
        image: "egusi.jpg", 
        slug: "egusi-soup", 
        excerpt: "A popular rich soup made from ground melon seeds and leafy vegetables.", 
        rating: 4.9, 
        difficulty: "Hard",
        ingredients: [
            { item: "Egusi (ground melon seeds)", qty: "2", unit: "cups" },
            { item: "Red Palm Oil", qty: "1", unit: "cup" },
            { item: "Beef/Goat Meat (boiled)", qty: "1", unit: "kg" },
            { item: "Dried Fish/Stock Fish", qty: "1", unit: "piece" },
            { item: "Uziza/Bitter Leaf (chopped)", qty: "2", unit: "cups" },
            { item: "Tatashe and Onions (blended)", qty: "1", unit: "cup" },
            { item: "Crayfish (ground)", qty: "1/4", unit: "cup" },
            { item: "Stock", qty: "3", unit: "cups" },
        ],
        instructions: [
            "Prepare Egusi: Mix the ground egusi with a little water to form a thick paste. Set aside.",
            "Fry Sauce: Heat palm oil until clear (do not bleach). Fry the blended pepper and onion mixture until dry. Add crayfish.",
            "Cook Egusi: Drop small balls of the egusi paste into the sauce. Do not stir immediately. Allow it to fry for 5-7 minutes to cook the seeds.",
            "Simmer: Add meat stock, boiled meat, and dried fish. Stir gently and allow to simmer for 15-20 minutes. The oil should float to the top.",
            "Finish: Stir in the chopped leafy vegetables (Uziza/Bitter leaf). Cook for 5 minutes and serve hot with Pounded Yam or Eba.",
        ]
    },
    { 
        id: 21, 
        title: "Pancakes (Fluffy)", 
        category: "Baking", 
        prepTime: "10 min", 
        cookTime: "15 min", 
        tags: ["Breakfast", "Sweet", "Quick"], 
        image: "pan.jpg", 
        slug: "fluffy-pancakes", 
        excerpt: "The ultimate recipe for thick, fluffy, American-style breakfast pancakes.", 
        rating: 4.6, 
        difficulty: "Easy",
        ingredients: [
            { item: "All-Purpose Flour", qty: "1.5", unit: "cups" },
            { item: "Baking Powder", qty: "3.5", unit: "tsp" },
            { item: "Salt", qty: "1/4", unit: "tsp" },
            { item: "Sugar", qty: "1", unit: "tbsp" },
            { item: "Milk", qty: "1.25", unit: "cups" },
            { item: "Egg", qty: "1", unit: "large" },
            { item: "Melted Butter", qty: "3", unit: "tbsp" },
        ],
        instructions: [
            "Mix Dry: Whisk together flour, baking powder, salt, and sugar.",
            "Mix Wet: In a separate bowl, whisk milk, egg, and melted butter.",
            "Combine: Pour the wet mixture into the dry ingredients. Mix until just combined. **Do not overmix; lumps are essential for fluffiness!**",
            "Cook: Pour 1/4 cup batter per pancake onto a preheated, lightly oiled griddle or non-stick pan. Cook until bubbles appear on the surface (2-3 minutes), then flip and cook for another 1-2 minutes.",
        ]
    },
    { 
        id: 22, 
        title: "Fish Pepper Soup", 
        category: "Main Dish", 
        prepTime: "15 min", 
        cookTime: "35 min", 
        tags: ["Spicy", "Soup", "Light"], 
        image: "fish.jpg", 
        slug: "fish-pepper-soup", 
        excerpt: "A light, intensely flavored, and spicy broth with fresh fish. Perfect for chilly evenings.", 
        rating: 4.7, 
        difficulty: "Medium",
        ingredients: [
            { item: "Fresh Fish (Catfish or Tilapia steaks)", qty: "500", unit: "g" },
            { item: "Uziza Seeds (ground)", qty: "1", unit: "tsp" },
            { item: "Eire (Ataiko) seeds (ground)", qty: "1/2", unit: "tsp" },
            { item: "Habanero Peppers (whole)", qty: "2-3", unit: "" },
            { item: "Scent Leaf or Basil", qty: "1/4", unit: "cup" },
            { item: "Onion (diced)", qty: "1/2", unit: "medium" },
            { item: "Stock/Water", qty: "4", unit: "cups" },
        ],
        instructions: [
            "Prep Fish: Clean and cut the fish into thick steaks. Gently rub with salt and lemon juice to firm the flesh.",
            "Broth Base: Boil water/stock. Add diced onion, pepper soup spices (Uziza, Eire), salt, and seasoning. Add the whole habanero peppers for controlled heat.",
            "Simmer: Allow the broth to boil vigorously for 10 minutes to extract the spice flavors.",
            "Add Fish: Gently add the fish steaks. Reduce heat and simmer for 10-15 minutes, or until the fish is cooked. Do not stir aggressively, or the fish will break.",
            "Finish: Stir in the scent leaves right before serving hot.",
        ]
    },
    { 
        id: 23, 
        title: "Garlic Parmesan Rolls", 
        category: "Baking", 
        prepTime: "30 min", 
        cookTime: "20 min", 
        tags: ["Bread", "Savoury", "Side"], 
        image: "garlic.jpg", 
        slug: "garlic-parmesan-rolls", 
        excerpt: "Soft, warm rolls drenched in garlic butter and Parmesan cheese. Highly addictive.", 
        rating: 4.5, 
        difficulty: "Easy",
        ingredients: [
            { item: "Pre-made or fresh pizza dough", qty: "500", unit: "g" },
            { item: "Unsalted Butter (melted)", qty: "1/2", unit: "cup" },
            { item: "Garlic (minced)", qty: "4", unit: "cloves" },
            { item: "Fresh Parsley (chopped)", qty: "2", unit: "tbsp" },
            { item: "Parmesan Cheese (grated)", qty: "1/2", unit: "cup" },
            { item: "Italian Seasoning", qty: "1", unit: "tsp" },
        ],
        instructions: [
            "Prep Dough: Cut the pizza dough into 1-inch pieces. Shape into small balls.",
            "Bake: Toss the dough balls in a greased baking pan. Bake at 190°C (375°F) for 15-20 minutes until lightly golden.",
            "Prepare Topping: While rolls bake, combine melted butter, minced garlic, parsley, and Italian seasoning.",
            "Finish: As soon as the rolls come out of the oven, brush them liberally with the garlic butter. Sprinkle immediately and generously with Parmesan cheese. Serve warm.",
        ]
    },
    { 
        id: 24, 
        title: "Grilled Tilapia", 
        category: "Main Dish", 
        prepTime: "15 min", 
        cookTime: "25 min", 
        tags: ["Seafood", "Healthy", "Quick"], 
        image: "tilapia.jpg", 
        slug: "grilled-tilapia", 
        excerpt: "Whole tilapia marinated in African spices and grilled until smoky and tender.", 
        rating: 4.8, 
        difficulty: "Medium",
        ingredients: [
            { item: "Whole Tilapia (cleaned and scaled)", qty: "2", unit: "fish" },
            { item: "Habanero Pepper (minced)", qty: "1", unit: "" },
            { item: "Ginger and Garlic Paste", qty: "1", unit: "tbsp" },
            { item: "Smoked Paprika", qty: "1", unit: "tsp" },
            { item: "Lemon Juice", qty: "1/4", unit: "cup" },
            { item: "Vegetable Oil", qty: "2", unit: "tbsp" },
            { item: "Salt and Pepper", qty: "To", unit: "taste" },
        ],
        instructions: [
            "Marinate: Score the fish deeply on both sides. Mix habanero, ginger/garlic paste, paprika, oil, lemon juice, salt, and pepper. Rub the marinade deep into the scores and cavity of the fish.",
            "Grill Prep: Preheat grill to medium-high heat. Lightly oil the grates to prevent sticking.",
            "Grill: Place the fish on the grill. Grill for 10-12 minutes per side (total 20-24 min), depending on thickness, until the flesh is flaky and opaque.",
            "Serve: Serve immediately with a side of fresh salsa or grilled plantains.",
        ]
    },
    { 
        id: 25, 
        title: "Yam Porridge (Asaro)", 
        category: "Main Dish", 
        prepTime: "20 min", 
        cookTime: "40 min", 
        tags: ["Traditional", "Comfort", "Tuber"], 
        image: "yam.jpg", 
        slug: "yam-porridge", 
        excerpt: "Creamy, tomato-based Nigerian porridge made with soft pounded yams.", 
        rating: 4.4, 
        difficulty: "Medium",
        ingredients: [
            { item: "Yam (white, peeled and cubed)", qty: "1/2", unit: "tuber" },
            { item: "Red Palm Oil", qty: "1/4", unit: "cup" },
            { item: "Fresh Tomatoes (blended)", qty: "2", unit: "medium" },
            { item: "Red Bell Pepper (blended)", qty: "1", unit: "" },
            { item: "Smoked Fish/Prawns", qty: "1/2", unit: "cup" },
            { item: "Onion (chopped)", qty: "1", unit: "medium" },
            { item: "Stock/Water", qty: "4", unit: "cups" },
            { item: "Leafy Greens (optional)", qty: "1", unit: "cup" },
        ],
        instructions: [
            "Boil Yam: Place the cubed yam in a pot and cover with water. Boil until the yam is almost tender (about 15 minutes). Drain and set aside.",
            "Fry Sauce: Heat palm oil. Sauté onions, then add the blended tomato/pepper mix. Fry for 10-15 minutes until the sauce is slightly thick.",
            "Simmer: Add the stock, smoked fish/prawns, salt, and seasoning cubes. Bring to a boil.",
            "Cook Porridge: Add the par-boiled yam cubes to the sauce. Reduce heat and simmer until the yam is very soft and starts to break down, forming the creamy porridge texture. Mash a few pieces gently to thicken.",
        ]
    },
]


// ====================================================================
// --- 4. Homepage Mock Data (Your Original Data) ---
// ====================================================================

/**
 * Featured Recipes (Subset of allRecipes, used for the homepage hero/sections)
 */
export const featuredRecipes = [
    {
        id: 1,
        title: "Classic Meat Pie", // Mapped to allRecipes[0]
        slug: "classic-meat-pie",
        image: "meatpie.jpg",
        time: "1h 30m", // Total time
        difficulty: "Medium",
        tags: ["Baking", "Breakfast", "Sweet"],
        excerpt: "Flaky, buttery scones prepped the night before for a perfect morning treat."
    },
    {
        id: 13,
        title: "Party Jollof Rice", // Mapped to allRecipes[12]
        slug: "party-jollof-rice",
        image: "jollof.jpg",
        time: "1h 30m", // Total time
        difficulty: "Medium",
        tags: ["Dinner", "Spicy", "Quick"],
        excerpt: "The iconic smoky, spiced tomato-based rice. Master the perfect party recipe."
    },
    {
        id: 6,
        title: "Rich Chocolate Cake", // Mapped to allRecipes[5]
        slug: "chocolate-cake",
        image: "cake.jpg",
        time: "1h 50m", // Total time
        difficulty: "Medium",
        tags: ["Dessert", "Chocolate", "Baking"],
        excerpt: "Intensely dark and fudgy cake with a rich ganache. Perfect for special occasions."
    },
    {
        id: 17,
        title: "Classic Tomato Stew", // Mapped to allRecipes[16]
        slug: "tomato-stew",
        image: "toma.jpg",
        time: "1h 20m", // Total time
        difficulty: "Easy",
        tags: ["Dinner", "Vegetarian", "Quick"],
        excerpt: "The foundational Nigerian stew. Versatile and essential for pairing with staples."
    },
];

export const inspirationSections = [
    {
        title: "Weekend Baking",
        link: "/recipes?filter=Baking",
        image: "/images/cat-baking.jpg",
        description: "Dive into sourdough, pastries, and holiday sweets."
    },
    {
        title: "Quick Weeknight Meals",
        link: "/recipes?filter=Easy",
        image: "/images/cat-quick.jpg",
        description: "Dinner on the table in under 30 minutes, without compromise."
    },
    {
        title: "Healthy & Wholesome",
        link: "/recipes?filter=Healthy", // Assuming 'Healthy' tag exists
        image: "/images/cat-healthy.jpg",
        description: "Nourishing, light recipes that are big on flavour."
    },
];